version: "3"
services:
  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./data.db:/directus/database/data.db  # Підключення вашого локального файлу data.db до контейнера
      - ./uploads:/directus/uploads           # Директорія для завантажених файлів
      - ./extensions:/directus/extensions
    environment:
      SECRET: "budanov"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "./data.db"
      WEBSOCKETS_ENABLED: "true"